[package]
name = "foreman"
description = "Toolchain manager for simple binary tools"
version = "1.0.3"
authors = [
  "Lucien Greathouse <me@lpghatguy.com>",
  "Matt Hargett <plaztiksyke@gmail.com>",
]
license = "MIT"
homepage = "https://github.com/Roblox/foreman#readme"
repository = "https://github.com/Roblox/foreman"
readme = "README.md"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "2.0.2"
env_logger = "0.7.1"
log = "0.4.8"
reqwest = { version = "0.10.1", features = ["json", "blocking"] }
semver = { version = "0.9.0", features = ["serde"] }
serde = { version = "1.0.104", features = ["derive"] }
rpassword = "4.0.5"
serde_json = "1.0.47"
structopt = "0.3.20"
toml = "0.5.6"
toml_edit = "0.1.5"
urlencoding = "2.1.0"
zip = "0.5"

[dev_dependencies]
assert_cmd = "2.0.2"
insta = "1.10.0"
tempfile = "3.3.0"
