[package]
name = "foreman"
description = "Toolchain manager for simple binary tools"
version = "0.5.0"
authors = ["Lucien Greathouse <me@lpghatguy.com>"]
license = "MIT"
homepage = "https://github.com/rojo-rbx/foreman#readme"
repository = "https://github.com/rojo-rbx/foreman"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "2.0.2"
env_logger = "0.7.1"
log = "0.4.8"
reqwest = { version = "0.10.1", features = ["json", "blocking"] }
semver = { version = "0.9.0", features = ["serde"] }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.47"
structopt = "0.3.9"
toml = "0.5.6"
zip = "0.5"
